teebot:
    token: '%telegram_token%'
    name: 'Example bot'
    url: 'https://api.telegram.org'
    file_url: 'https://api.telegram.org/file/bot'
    method: 'GET'
    bot_prefix: 'bot'
    timeout: 3
    events:
        -
            command: 'Me'
            type: 'Command'
            class: Teebot\Bot\Example\Command\Me
        -
            command: '~foo~'
            type: 'RegexpCommand'
            class: Teebot\Bot\Example\Command\Foo
    logger:
        filename: 'Bot/Example/logs/log.txt'